export const SET_ERROR = 'SET_ERROR';
export const AUTH_USER = 'AUTH_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const RIG_USER = 'RIG_USER';
export const FETCH_USER = 'FETCH_USER';
export const GOOGLE_AUTH = 'GOOGLE_AUTH';
export const GOOGLE_LOGOUT = 'GOOGLE_LOGOUT';

export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const SET_CATEGORY = 'SET_CATEGORY';
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';
export const REMOVE_CATEGORY = 'REMOVE_CATEGORY';
export const SELECT_CATEGORY = 'SELECT_CATEGORY';

export const FETCH_MEALS = 'FETCH_MEALS';
export const FETCH_MEALS_BY_CATEGORY = 'FETCH_MEALS_BY_CATEGORY';
export const FETCH_MEALS_BY_USER = 'FETCH_MEALS_BY_USER';
export const SET_MEAL = 'FETCH_MEAL';
export const UPDATE_MEAL = 'UPDATE_MEAL';
export const REMOVE_MEAL = 'REMOVE_MEAL';
export const SELECT_MEAL = 'SELECT_MEAL';
